from .opSVM import OpSVMTrain
from .opSVM import OpSVMPredict
from .opState import OpStateTrain
from .opState import OpStatePredict
from .opDeep import OpDeepTrain
from .opMLP import OpMLPTrain
from .opMLP import OpMLPPredict
from .opRF import OpRFTrain
from .opRF import OpRFPredict
