from opExponentiallySegmentedPattern import OpExponentiallySegmentedPattern
from opExponentiallySegmentedPattern import OpNormalize
from opDiscretize import OpDiscretize
from opDiscretize import OpClassFromOneHot
